gitRepoUrl = "https://github.com/xSwezan/SuperQuest"
gitSourceBranch = "main"

classorder = [

]

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "Powerful Quest System with Rich API!"
favicon = "/Icon.png"