[package]
name = "eddie/module_name"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Maid = "flamenco687/maid@3.2.2"
Roact = "roblox/roact@1.4.2"
Roact-spring = "chriscerie/roact-spring@1.0.0"
DataStore2 = "nidoxs/datastore2@1.4.0"
Promise = "evaera/promise@4.0.0"
Component = "sleitnick/component@2.4.6"
Knit = "sleitnick/knit@1.4.7"