[package]
name = "nidoxs/datastore2"
license = "MIT"
version = "1.4.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Kampfkarren"]
description = "DataStore2 ported to wally"

[dependencies]